version: '3'

services:
  db_test:
    build: ./database
    container_name: test_database_test
    restart: always
    env_file: ./env_file_general.env
    ports:
      - "5432:5432"
  
  gaga:
    build:
      context: .
    container_name: gaga_start
    env_file: ./env_file_general.env
    ports:
      - "3000:3000"
    volumes:
      - gaga_data:/pages/data/
    
  # beyonce:
  #   image: python:3
  #   command: ['echo', 'This works!']
  #   environment:
  #     PRINT: 'True'
  #     POSTGRES_USER=${POSTGRES_USER}

  #   depends_on:
  #     - gaga
  #   links:
  #     - gaga

  enginx_test:
    build: ./nginx
    container_name: test_nginx_test
    ports:
      - "45:45"
    # depends_on:
    #   - "princess"

  # enginx_protection:
  #   build: ./failtoban
  #   container_name: nginx_protection
  #   environment:
  #     - ./env
  #   volumes:
  #     - .:/var/logs/

volumes:
  gaga_data: {}
