#!/bin/bash

set -o errexit

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
    CREATE DATABASE $NEW_DB;
    GRANT ALL PRIVILEGES ON DATABASE $NEW_DB TO $DB_USER;
EOSQL

"$@"