version: '3.7'

services:
  app:
    build: ./website/mydjango
    container_name: website_app_prod
    env_file:
      - ./env_files/env_prod.env
      - ./env_files/django.env
      - ./env_files/db_env.env
    volumes:
      - .:/code
      - ./var/gunicorn/log:/var/log/gunicorn/
    ports:
      - "4000:8000"
    depends_on:
      - "db"
    links:
      - "db"

  app_2:
    build: ./website/mydjango
    container_name: website_app_dev
    env_file:
      - ./env_files/env_dev.env
      - ./env_files/django.env
      - ./env_files/db_env.env
    volumes:
      - .:/code
    ports:
      - "6000:8000"
    depends_on:
      - "db"
    links:
      - "db"

  db:
    build: ./database
    container_name: postgres_database
    env_file: ./env_files/db_env.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - PostgresData:/var/lib/postgresql/data/

  enginx:
    build: ./nginx
    container_name: app_nginx
    restart: always
    ports:
      - "20:80"
    depends_on:
      - "app"
    volumes:
      - ./var/certbot:/etc/letsencrypt/

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - "app"
      - "enginx"
      - "db"

  failtoban:
    build: ./failtoban
    container_name: failtoban
    depends_on:
      - "app"
      - "enginx"
    links:
      - "enginx"

  certbot:
    build: ./cert
    container_name: certbot
    volumes:
      - ./var/certbot:/etc/letsencrypt

volumes:
  PostgresData: {}


nginx:
  volumes:
    - ./var/data:/etc/letsencrypt

certbot:
  volumes:
    - ./var/data:/etc/letsencrypt