version: '3'

services:
  db:
    build: ./database
    container_name: postgres_database
    env_file: ./env_files/db_env.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build: ./website/docke
    container_name: website_app_prod
    env_file: ./env_files/env_prod.env
    volumes:
      - .:/code
    ports:
      - "4000:8000"
    depends_on:
      - "db"
    links:
      - "db"

  enginx:
    build: ./nginx
    container_name: app_nginx
    restart: always
    ports:
      - "20:80"
    volumes:
      - nginx_logs:/var/log/nginx/
    depends_on:
      - "app"

  # fail_to_ban:
  #   build: ./failtoban
  #   container_name: server_protection
  #   restart: always
    
volumes:
  postgres_data: {}
  auth_log: {}
  nginx_logs: {}