version: '3'

services:
  db:
    build: ./database
    container_name: postgres_database
    env_file: ./env_file_general.env
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=job_default
    #   - POSTGRES_PASSWORD=Constance97170
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_database:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/

  jobsite:
    build: .
    container_name: job_startup
    env_file: ./env_file_general.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    links:
      - "db"

  enginx:
    build: ./nginx
    container_name: job_nginx
    restart: always
    # environment:
    #   - NGINX_PORT=80
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "jobsite"

  # enginxprotekt:
  #   build: ./failtoban
  #   container_name: nginx_protection
  #   volumes:
  #     - ./etc/fail2ban/jail.local:/etc/fail2ban/jail.local
  #   depends_on:
  #     - enginx
 
volumes:
  postgres_data: {}
    