version: '3'

services:
  db:
    build: ./database
    container_name: postgres_database
    env_file: ./env_files/db_env.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app_dev:
    build: .
    container_name: website_app
    env_file: ./env_files/env_dev.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    links:
      - "db"

  enginx:
    build: ./nginx
    container_name: app_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/log:/var/log/nginx/
    depends_on:
      - "app_dev"

  # enginxprotekt:
  #   build: ./failtoban
  #   container_name: nginx_protection
  #   volumes:
  #     - ./etc/fail2ban/jail.local:/etc/fail2ban/jail.local
  #   depends_on:
  #     - enginx
 
volumes:
  postgres_data: {}
    