#!/bin/bash

set -o errexit

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $DB_USER WITH ENCRYPTED PASSWORD $DB_PASSWORD;
    \du
    CREATE DATABASE $POSTGRES_DB OWNER $DB_USER;
    \list
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $DB_USER;
EOSQL

"$@"